# Generated by Django 4.1.4 on 2023-01-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='srno',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.department'),
        ),
    ]
